name: Build FluidSynthPads

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config wget p7zip-full git cmake libglib2.0-dev libasound2-dev lv2-dev

    - name: Install FluidSynth
      run: |
        git clone https://github.com/FluidSynth/fluidsynth.git
        cd fluidsynth
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ../..

    - name: Build FluidSynthPads
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FluidSynthPads.lv2
        path: FluidSynthPads.lv2/

    - name: Cleanup
      run: make clean
      if: always()
