name: Build FluidSynthPads

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-arm64
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config wget p7zip-full git cmake libglib2.0-dev libasound2-dev lv2-dev

    - name: Build FluidSynth
      run: |
        git clone https://github.com/FluidSynth/fluidsynth.git
        cd fluidsynth
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ../..

    - name: Download Soundfont
      run: |
        mkdir -p FluidSynthPads.lv2
        cd FluidSynthPads.lv2
        wget https://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_synthpad.sf2.tar.7z
        7z x fluidr3gm_synthpad.sf2.tar.7z
        7z x fluidr3gm_synthpad.sf2.tar
        mv fluidr3gm_synthpad.sf2 FluidPlug.sf2
        cd ..

    - name: Build Plugin
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FluidSynthPads.lv2
        path: FluidSynthPads.lv2/